plugins {
  alias(libs.plugins.kotlin.plugin.serialization)
}

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

kotlin {
  compilerOptions {
    optIn.add("kotlin.uuid.ExperimentalUuidApi")
  }
}

dependencies {
  api libs.ashley
  api libs.gdx.core
  api libs.ktx.app
  api libs.ktx.ashley
  api libs.ktx.async
  api libs.ktx.collections
  api libs.ktx.graphics
  api libs.ktx.json
  api libs.ktx.log
  api libs.ktx.math
  api libs.kotlin.stdlib
  api libs.kotlinx.coroutines
  implementation libs.kotlinx.serialization.json
  implementation project(':utils')

//  api "com.badlogicgames.ashley:ashley:$ashleyVersion"
//  api "com.badlogicgames.gdx:gdx:$gdxVersion"
//  api "io.github.libktx:ktx-ashley:$ktxVersion"
//  api "io.github.libktx:ktx-async:$ktxVersion"
//  api "io.github.libktx:ktx-collections:$ktxVersion"
//  api "io.github.libktx:ktx-graphics:$ktxVersion"
//  api "io.github.libktx:ktx-json:$ktxVersion"
//  api "io.github.libktx:ktx-log:$ktxVersion"
//  api "io.github.libktx:ktx-math:$ktxVersion"
//  api "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
//  api "org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlinxCoroutinesVersion"

  if (enableGraalNative == 'true') {
//    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
    implementation libs.graal.helper.annotations
  }
}
