plugins {
  alias(libs.plugins.kotlin.plugin.serialization)
}

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

kotlin {
  compilerOptions {
    optIn.add("kotlin.uuid.ExperimentalUuidApi")
    optIn.add("kotlin.concurrent.atomics.ExperimentalAtomicApi")
  }
}

dependencies {
  api libs.ashley
  api libs.ktx.actors
  api libs.gdx.core
  api libs.ktx.app
  api libs.ktx.ashley
  api libs.ktx.async
  api libs.ktx.collections
  api libs.ktx.graphics
  api libs.ktx.json
  api libs.ktx.log
  api libs.ktx.math
  api libs.ktx.scene2d
  api libs.ktx.style
  api libs.kotlin.stdlib
  api libs.kotlinx.coroutines
  implementation libs.kotlinx.serialization.json
  implementation libs.ktor.network
  implementation libs.ktor.client.cio
  implementation libs.ktor.client.content.negotiation
  implementation libs.ktor.client.core
  implementation libs.ktor.serialization.kotlinx.json

  if (enableGraalNative == 'true') {
    implementation libs.graal.helper.annotations
  }

  testImplementation libs.junit.jupiter
  testRuntimeOnly libs.junit.platform.launcher

  testImplementation libs.gdx.backend.headless
  testRuntimeOnly(variantOf(libs.gdx.platform) { classifier("natives-desktop") })

  implementation(project(":common"))
}

tasks.test {
  useJUnitPlatform()
}
